create table public.colaboradores (
  -- id bigint generated by default as identity not null,
  id uuid primary key default gen_random_uuid(),

  nombre text not null,
  puesto text not null,
  codigo_interno text not null,
  f_ingreso date not null,
  nss_imss text not null,
  curp text not null,
  rfc text not null,
  vigencia date not null,
  foto_url text not null,
  descripcion text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint colaboradores_pkey primary key (id)
) TABLESPACE pg_default;

alter table public.colaboradores enable row level security;


-- =========================================================
-- PRIVILEGIOS
-- =========================================================

revoke all on table public.colaboradores
from anon, authenticated;

grant select, insert, update
on table public.colaboradores
to authenticated;


-- =========================================================
-- POLICIES
-- =========================================================

create policy "Colaboradores visibles para usuarios autenticados"
on public.colaboradores
for select
to authenticated
using (true);


create policy "Usuarios autenticados pueden registrar colaboradores"
on public.colaboradores
for insert
to authenticated
with check (true);


create policy "Usuarios autenticados pueden editar colaboradores"
on public.colaboradores
for update
to authenticated
using (true)
with check (true);


-- =========================================================
-- FUNCIÓN PARA DETALLE PÚBLICO
-- =========================================================

create or replace function public.obtener_colaborador_publico(
  p_id uuid
)
returns table (
  id uuid,
  nombre text,
  puesto text,
  codigo_interno text,
  f_ingreso date,
  nss_imss text,
  curp text,
  rfc text,
  vigencia date,
  foto_url text,
  descripcion text
)
language sql
security definer
stable
set search_path = public
as $$
  select
    e.id,
    e.nombre,
    e.puesto,
    e.codigo_interno,
    e.f_ingreso,
    e.nss_imss,
    e.curp,
    e.rfc,
    e.vigencia,
    e.foto_url,
    e.descripcion
  from public.colaboradores e
  where e.id = p_id;
$$;


revoke all
on function public.obtener_colaborador_publico(uuid)
from public;

grant execute
on function public.obtener_colaborador_publico(uuid)
to anon, authenticated;